### PR TITLE
angularls: Add typescript dependency

### PR DESCRIPTION
**Pull request by ilyasakin**
`@angular/language-server` package needs the `typescript` package to be present.

Without the `typescript` package, it outputs following log message:
```
[ERROR][2021-11-15 11:39:05] .../vim/lsp/rpc.lua:462	"rpc"	"/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/.bin/ngserver"	"stderr"	"/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:219\n      throw new Error(`Failed to resolve '${packageName}' with minimum version '${minVersion}' from ` + JSON.stringify(probeLocations, null, 2));\n      ^\n\nError: Failed to resolve 'typescript/lib/tsserverlibrary' with minimum version '4.3' from [\n  \"/home/ashnwor/.local/share/nvim/lsp_servers/angularls\"\n]\n    at resolveWithMinVersion (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:219:13)\n    at resolveTsServer (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:228:14)\n    at requireOverride (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:297:57)\n    at dist/server/logger.js (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:414:27)\n    at __require (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:313:44)\n    at Object.<anonymous> (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:4557:16)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\n"
```

then exits with status code 1.

### CODE REVIEW

**Comment by williamboman** [comment]
Hello! The angular server is configured to look for a typescript installation in the project it's started in. Do you have typescript installed in your project?

**Comment by ilyasakin** [comment]
> Hello! The angular server is configured to look for a typescript installation in the project it's started in. Do you have typescript installed in your project?

Hello, I forgot that I did override the default config. As seen in the following log, lsp tries to look @angular/language-server in the project folder:
```
[ERROR][2021-11-15 18:21:57] .../vim/lsp/rpc.lua:462	"rpc"	"/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/.bin/ngserver"	"stderr"	"/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:3509\n      throw new Error(`Failed to resolve '${packageName}' with minimum version '${minVersion}' from ` + JSON.stringify(probeLocations, null, 2));\n      ^\n\nError: Failed to resolve '@angular/language-service' with minimum version '13.0' from [\n  \"/home/ashnwor/development/todo-app-gui/node_modules\"\n]\n    at resolveWithMinVersion (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:3509:13)\n    at resolveNgLangSvc (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:3550:14)\n    at main (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:4572:54)\n    at Object.<anonymous> (/home/ashnwor/.local/share/nvim/lsp_servers/angularls/node_modules/@angular/language-server/index.js:4598:1)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\n    at Module.require (internal/modules/cjs/loader.js:974:19)\n    at require (internal/modules/cjs/helpers.js:93:18)\n"
```
Particularly this bit: `Error: Failed to resolve '@angular/language-service' with minimum version '13.0' from [\n  \"/home/ashnwor/development/todo-app-gui/node_modules\"\n]\n    at resolveWithMinVersion`

So, I had to override the default config to point the config --which i totally forgot-- to the installed server at `.local/share/nvim/lsp_servers/angularls`

Like this:
```lua
  if server.name == 'angularls' then
    local cmd = {
      server.root_dir .. '/node_modules/.bin/ngserver',
      '--stdio',
      '--tsProbeLocations',
      server.root_dir,
      '--ngProbeLocations',
      server.root_dir,
    }

    opts.cmd = cmd
    opts.on_new_config = function(new_config)
      new_config.cmd = cmd
    end
  end
```

So, this PR is probably irrelevant to the actual problem. Could something wrong with my config?

**Comment by williamboman** [comment]
> So, I had to override the default config to point the config --which i totally forgot-- to the installed server at `.local/share/nvim/lsp_servers/angularls`

You should not be doing this, pointing it to this location will make it crash as only the LSP server is installed there. They seem to have a good guide over at https://angular.io/guide/language-service, maybe that'd be helpful.



> Could something wrong with my config?

Yeah don't override the cmd, no need to. Instead make sure `typescript` and `@angular/language-service` is installed in the project you're working on.

**Comment by ilyasakin** [comment]
> Yeah don't override the cmd, no need to. Instead make sure typescript and @angular/language-service is installed in the project you're working on.

Oh, ok. I now realized that the server looking for an angular language server in the project folder is the intended behavior.

But this is still doesn't make any sense to me since the official language server extension for vscode uses `.vscode/extensions/angular.ng-template-13.0.0/server/bin/ngserver`. Having a separate local installation of ngserver seems redundant for me. 

Also, most of the angular projects don't have angular language server dependency. So, with default behavior, I need to install angular language server locally before writing any code for upstream projects -which I think is no big deal, but still annoying-.

Wouldn't be better to use global `ngserver` like VSCode and Webstorm (>2019.1) do?

**Comment by rybertm** [comment]
@williamboman is there anyway to have this check a global version of either? I have a `angular` 9 project which can't use with neovim right now because it requires `typescript: ^4.0.3` but the `angular` compiler only supports up until `typescript: 3.9.0`, so I can't really upgrade the `typescript` version. Or am I missing something?

**Comment by lucasvianav** [comment]
> @williamboman is there anyway to have this check a global version of either? I have a `angular` 9 project which can't use with neovim right now because it requires `typescript: ^4.0.3` but the `angular` compiler only supports up until `typescript: 3.9.0`, so I can't really upgrade the `typescript` version. Or am I missing something?

I'm having the exact same problem, totally unable to use angularls right now. Either this or having the option to make the plugin install typescript alongside angularls (like I suppose this PR does, which I'd prefer) would be great.

(also thanks for the great plugin)

**Comment by williamboman** [comment]
Ah I see. I read up on how VSCode does it and it seems like they [ship typescript](https://github.com/angular/vscode-ng-language-service#versioning) and that it's the recommended one.

**Review by williamboman — APPROVED** [review]
LGTM!

**Comment by williamboman** [comment]
I realized the cmd probably needs changing too - does #266 work for you guys?

**Comment by rybertm** [comment]
> I realized the cmd probably needs changing too - does #266 work for you guys?

It does. Thanks for the quick response and fix.

**Comment by lucasvianav** [comment]
> I realized the cmd probably needs changing too - does #266 work for you guys?

Works for me as well, thank you so much :)

**Pull request merged**
