### PR TITLE
add julials

### PR DESCRIPTION
**Pull request by hasundue**

### CODE REVIEW

**Comment by hasundue** [comment]
Sorry I forgot to update README

**Comment by williamboman** [comment]
Hello! Cool! Have you seen the discussions in #143 btw? Due to how the Julia package manager works, we lose a lot of the control and guarantees that is necessary to ensure the plugin behaves in a reliable manner (this is discussed more in #143). 

I've spent some time today looking into how the VSCdoe extension does this, and it seems like they bundle the LanguageServer and all its dependencies, [like so](https://github.com/julia-vscode/julia-vscode/blob/master/scripts/environments/languageserver/Manifest.toml). The server is started [like so](https://github.com/julia-vscode/julia-vscode/blob/master/src/extension.ts#L229-L240), which runs [main.jl](https://github.com/julia-vscode/julia-vscode/blob/master/scripts/languageserver/main.jl). From this, I've been able to set up a simplified version which seems to be working pretty well actually.

Could you see whether branch `add-julials` (#429) works fine for you? I'm not a Julia dev so I can't really tell. It seems a bit "broken" on projects that only has a `Project.toml` and not a `Manifest.toml` (it wont find dependencies, you need to run `Pkg.instantiate()` and then restart neovim for the LSP to find dependencies).

**Comment by hasundue** [comment]
Oh, sorry, I didn't notice you already worked on julia.
Sure, I'm looking into that.

**Comment by hasundue** [comment]
I just removed my changes which are no longer needed and formatted the script to a "Julia style". https://github.com/williamboman/nvim-lsp-installer/pull/432

**Comment by williamboman** [comment]
> Oh, sorry, I didn't notice you already worked on julia. Sure, I'm looking into that.

No worries! We had actually gotten a bit stuck haha, this PR prompted me to take a 2nd look :)

**Pull request closed without merging**
