### PR TITLE
Fix eslint pnp cmd override example

### LINKED ISSUE #507: Eslint with PNP example no longer seems to work
### Problem description

Solution described [here](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/eslint/README.md#eslint-in-projects-that-use-pnp) for using the eslint lsp with pnp does not appear to work since the change to using cmd_env. Is there a way to resolve the cmd with the cmd_env prepended for this usecase?

### Neovim version (>= 0.6)

NVIM v0.7.0-dev+1135-gfdea15723
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin LM-C02DR28LMD6R 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### I've recently downloaded the latest plugin version of both nvim-lsp-installer and nvim-lspconfig

- [X] Yes

### Affected language servers

eslint

### Actual behavior

local install of eslint is not resolved and there is a log from lspconfig stating that they could not find eslint library

### Expected behavior

Local install of eslint would be resolved and lsp would work without global installation of eslint

### Healthcheck output

```shell
nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **gzip**: `Apple gzip 352.40.6`
  - OK: **curl**: `curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0`
  - OK: **node**: `v14.17.0`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: **Go**: `go version go1.17.2 darwin/amd64`
  - OK: **java**: `Ok`
  - OK: **python3**: `Python 3.9.10`
  - OK: **javac**: `javac 15.0.2`
  - OK: **npm**: `8.1.2`
  - OK: **RubyGem**: `3.0.3.1`
  - OK: **pip3**: `pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`
```

### Screenshots

Screen Shot 2022-02-26 at 12 45 16 AM

### PR DESCRIPTION
**Pull request by NICHTJ3**
Since the change to using $PATH to resolve servers the current eslint pnp solution does not work. This solution works with the new changes

Fixes #507

### CODE REVIEW

**Comment by NICHTJ3** [comment]
So as this turns out this isn't really a complete solution either. This still doesn't work with projects that use pnpm. I've done this in my config to work around them both but it feels a little hacky.

```lua
local eslint_config = require("lspconfig.server_configurations.eslint")
local lspconfig = require('lspconfig')

local M = {}

local function get_cmd()

    local cmd = eslint_config.default_config.cmd

    local buffer_location = vim.api.nvim_buf_get_name(0)

    local pnpm = lspconfig.util.root_pattern('pnpm-lock.yml', 'pnpm-lock.yaml')(
                    buffer_location)

    local yarn2 = lspconfig.util.root_pattern('.pnp.cjs', '.pnp.js')(
                      buffer_location)

    if pnpm and vim.fn.executable('pnpm') == 1 then
        cmd =
            vim.list_extend({"pnpm", "exec"}, eslint_config.default_config.cmd)
    end
    --
    if yarn2 and vim.fn.executable('yarn') == 1 then
        cmd =
            vim.list_extend({"yarn", "exec"}, eslint_config.default_config.cmd)
    end
    return cmd
end

M.config = {on_new_config = function(config) config.cmd = get_cmd() end}

return M

```

**Comment by NICHTJ3** [comment]
Good catch on that 👍

**Comment by williamboman** [comment]
@NICHTJ3 Does the latest change work? Should we merge this?

**Comment by NICHTJ3** [comment]
The latest change seems to stop it working. It seems to work without the `--` before passing the options though

**Comment by williamboman** [comment]
> The latest change seems to stop it working. It seems to work without the `--` before passing the options though

Ah of course. That `--` is shell-specific syntax. So this is good to go now :+1:?

**Comment by NICHTJ3** [comment]
@williamboman yeah it is 👍Sorry for the late reply works been hectic

**Comment by williamboman** [comment]
No worries, thanks for reporting!

**Pull request closed without merging**
