### PR TITLE
Use arm64 binary on linux for sumneko_lua

### PR DESCRIPTION
**Pull request by aidos**
Hello! Firstly, thanks for the amazing plugin.

I've had a [PR merged](https://github.com/sumneko/lua-language-server/pull/892) on sumneko_lua to build the arm64 binary on linux for the releases. There hasn't been a release yet, but once there is, this  PR _should_ be what we want for the install step.

### CODE REVIEW

**Comment by williamboman** [comment]
Hello! Cool, will try to keep an eye on new releases then!

**Review by williamboman — APPROVED** [review]

**Comment by aidos** [comment]
Awesome! Thanks.

**Comment by williamboman** [comment]
Hello! I've been keeping an eye on new releases but it seems like there are some issues with getting arm64 builds working. I'll close this for now to not have lingering issues/PRs, happy to reopen once it's ready!

**Comment by aidos** [comment]
Yup, I’m keeping an eye on it too. Thanks.

**Comment by aidos** [comment]
Looks like the ARM build is working now so hopefully we'll see a release soon.

**Comment by aidos** [comment]
Looks like the ARM build is working now so hopefully we'll see a release soon.

**Review by williamboman — APPROVED** [review]
With the latest 3.0.0 release this is now available!

**Pull request merged**
