### PR TITLE
add get_server({server_name}) to public Lua API

### LINKED ISSUE #22: [Feature Request] Expose get_server function
I'm trying to do something like this:
```lua
local lsp_installer = require('nvim-lsp-installer')
local _, server = lsp_installer.get_server("rust-analyzer")

if not server.is_installed() then
    server.install()
end
```

I want to do this so that I only install the language server if a specific plugin is loaded (in this case `rust-tools.nvim`).

But I'm unable to because the `get_server` function isn't exposed. Would it be possible to expose it?

### PR DESCRIPTION
**Pull request by williamboman**
Closes #22.

### CODE REVIEW

**Comment by williamboman** [comment]
@Akeboshiwind wdyt?

**Comment by Akeboshiwind** [comment]
Nice, that looks good to me.

It's much nicer to have this as part of the API rather than having to reach
for the internals :D

**Comment by williamboman** [comment]
> It's much nicer to have this as part of the API rather than having to reach for the internals :D

Yeah for sure!

**Comment by Akeboshiwind** [comment]
Thanks for the quick turn around :D

**Pull request merged**
