### PR TITLE
sumneko_lua: use prebuilt dist

### LINKED ISSUE #78: More faster installation of the sumneko_lua server...
Hey I am here again 😄 

Well the installation for sumneko is more easy will dont need compile with ninja the binaries are [here](https://github.com/sumneko/vscode-lua)

Can you clone the repo and use the binaries example with lspconfig :) 

https://github.com/TeoDev1611/AstroVim/blob/astro/lua/lsp/lsp-servers/init.lua#L10

Using this repo

Great work with the windows support 🚀

### PR DESCRIPTION
**Pull request by williamboman**
Resolves #78.

### CODE REVIEW

**Comment by williamboman** [comment]
Hey @TeoDev1611 could you give this branch a try 🙏?

**Comment by TeoDev1611** [comment]
Ok 👌👍

**Comment by williamboman** [comment]
I got this working on Windows (after installing wget and unzip via choco). Is this a weird requirement for Windows users, or is it common for these to be installed?

**Comment by TeoDev1611** [comment]
@williamboman  why don't use powershell ? example

```
powershell -Command iwr -Uri where i download -OutFile lua.zip
```

**Comment by williamboman** [comment]
That is... a lot of foreign words and weird syntax 🙈. Me and Powershell are not friends unfortunately.

If you could give me the commands to the following operations I could make it work

1) download a remote file over HTTP (i.e.,`wget` or `curl` in Unix) and save it to a specific file name locally
1) unzip a file
1) remove a file
1) remove a directory

**Comment by TeoDev1611** [comment]
Let me try make this :)

**Comment by TeoDev1611** [comment]
```powershell
iwr -Uri https://github.com/sumneko/vscode-lua/releases/download/v2.3.6/lua-2.3.6.vsix -OutFile lua.zip
Expand-Archive -Path .\lua.zip -DestinationPath wherever:)
Remove-Item -Force '..\path\to\whatever\`[Content_Types`].xml'
Remove-Item -Force .\path\to\whatever\extension.vsixmanifest
Remove-Item -Force .\lua.zip
```
This download the file expand remove the unused files and remove the zip @williamboman

**Comment by TeoDev1611** [comment]
If you need run this in a file with powershell example:

```
powershel -File powershelScript.ps1
```

**Comment by williamboman** [comment]
Closing in favor of #85. @TeoDev1611 I added Windows support for more than just Lua in that branch, feel free to try it out and comment if you find any issues :pray:!

**Pull request closed without merging**
