### PR TITLE
feat: add ensure_installed to setup table

### PR DESCRIPTION
**Pull request by williamboman**

### CODE REVIEW

**Comment by williamboman** [comment]
Hey @MurdeRM3L0DY! Yes! , see #638, wdyt?

**Comment by MurdeRM3L0DY** [comment]
I think you could also add an `exclude` key for servers users might prefer to install with their system's package manager(clangd for example). Users would be able to configure like so:
```lua
require('nvim-lsp-installer').setup {
  ...
  servers = {
    ensure_installed = { ... } -- or "automatic",
    exclude = { ... },
  },
  ...
}
```

Although, on a second thought. this might make configuration for users who use both nvim-lspconfig together with other lsp plugins awkward(rust-tools for example). So some part of me thinks we shouldn't have the automatic option in the first place since most likely users will only ever install the servers once on a single machine.

**Comment by williamboman** [comment]
Ah, good point!

> So some part of me thinks we shouldn't have the automatic option in the first place since most likely users will only ever install the servers once on a single machine.

This is anecdotal of course but I jump between machines quite a lot, and apart from on my main dev machine I have no idea what's installed, so having something to take care of that for me would help tremendously.

**Comment by MurdeRM3L0DY** [comment]
That's also a fair point. Most of lsp extention plugins call lspconfig setup anyways.

**Comment by MurdeRM3L0DY** [comment]
Alternatively we could install servers automatically when users configure via lspconfig and reserve `ensure_installed` for servers which may or may not be used by lspconfig.

**Comment by williamboman** [comment]
I kept `ensure_installed` as-is, and introduced a `automatic_installation` setting instead. Brain is fried, not sure if naming or docs make any sense. Wdyt?

**Comment by MurdeRM3L0DY** [comment]
Yeahhh, naming is hard :) I can't think of a better name as well.

**Pull request merged**
