### PR TITLE
leverage PATH for locating local executables

### LINKED ISSUE #279: lsp server binaray script add parameter
**Is your feature request related to a problem? Please describe.**
I want change clangd cmd options, e.g. `clangd --background-index --compile-commands-dir=xxx`
I use `path.concat { server.get_server_root_path('clangd'), 'clangd'` get clangd path, it is a script
```
cat ~/.vim/.cache/lsp_servers/clangd/clangd
#!/usr/bin/env sh
exec "/home/fcying/.vim/.cache/lsp_servers/clangd/clangd_13.0.0/bin/clangd"
```
It not accept parameter, add `$@` can work.
```
exec "/home/fcying/.vim/.cache/lsp_servers/clangd/clangd_13.0.0/bin/clangd" $@
```
Another way, it there any way to get clangd's real path? 
`/home/fcying/.vim/.cache/lsp_servers/clangd/clangd_13.0.0/bin/clangd`

### PR DESCRIPTION
**Pull request by williamboman**
Now that https://github.com/neovim/neovim/pull/16430 is merged this is now possible. Will have to think of how to actually roll this out, requiring a nightly neovim build is a bit excessive.

Fixes #279.

### CODE REVIEW

**Comment by mjlbach** [comment]
Neovim 0.6 is releasing next tuesday fwiw, along with lspconfig's first tagged release (0.1.0)

**Comment by williamboman** [comment]
I've given this some pretty exhaustive testing (both automatic via https://github.com/williamboman/nvim-lspconfig-test but also manual). Should be good to go.

**Comment by thetic** [comment]
Does this break `:checkhealth lspconfig` for anyone else? The servers themselves seem to run fine.

**Comment by kylo252** [comment]
> Does this break `:checkhealth lspconfig` for anyone else? The servers themselves seem to run fine.

Yup it's broken, since that healthcheck is ignoring `cmd_env` 😞

**Comment by thetic** [comment]
that's a bummer. is there an open issue against lspconfig? I can't find one.

**Comment by kylo252** [comment]
> that's a bummer. is there an open issue against lspconfig? I can't find one.

fixed in https://github.com/neovim/nvim-lspconfig/pull/1636

**Pull request merged**
